apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-rc
  labels:
    name: web
    tier: backend
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      name: rc-httpd
      labels:
        tier: backend
        name: web
    spec:
      containers:
      - name: rc-cont
        image: httpd
        ports:
        - containerPort: 80
